[build]
target = "loongarch64-unknown-none"

[target.loongarch64-unknown-none]
rustflags = [
    "-Clink-arg=-Tsrc/linker_loongarch.ld",
    "-Clink-arg=-nostdlib",
    "-Clink-arg=-static",
    "-Cforce-frame-pointers=yes",
    "-Ctarget-feature=-ual,-lsx,-lasx,-lvz",
]

linker = "loongarch64-linux-musl-gcc"
[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/BiorelaxA/smoltcp.git?branch=main"]
git = "https://github.com/BiorelaxA/smoltcp.git"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/li041/virtio-drivers?branch=lxh"]
git = "https://github.com/li041/virtio-drivers"
branch = "lxh"
replace-with = "vendored-sources"

[source."git+https://github.com/rcore-os/riscv"]
git = "https://github.com/rcore-os/riscv"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"